name: split_it
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0

  #Firebase
  firebase_core: ^1.3.0

  #Login Social
  google_sign_in: ^5.2.1
  sign_in_with_apple: ^3.0.0

  #Facilitar os testes
  mocktail: ^0.1.4

  #Facilitar os loadings
  shimmer: ^2.0.0
  intl: ^0.17.0

  #Gerencia de estado
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.3+2
  mobx_codegen: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7

flutter:

  uses-material-design: true

  assets:
    - assets/images/
